events {}
http {
  upstream legacy { server legacy-ofbiz-app:8443; }
  upstream invoices { server modern-accounting-invoice-service:8080; }
  server {
    listen 443 ssl;
    ssl_certificate /etc/nginx/certs/local.crt;
    ssl_certificate_key /etc/nginx/certs/local.key;

    location = /accounting/control/findInvoices { proxy_pass http://invoices; proxy_set_header Host $host; }
    location ^~ /api/accounting/invoices { proxy_pass http://invoices; proxy_set_header Host $host; }
    location ^~ /modern/accounting/invoices { proxy_pass http://invoices; proxy_set_header Host $host; }

    location / {
      proxy_pass https://legacy;
      proxy_ssl_verify off;
      proxy_set_header Host localhost:18443;
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header Accept-Encoding "";
      sub_filter_once off;
      sub_filter 'https://localhost:18443' 'https://localhost:18080';
    }
  }
}
